name: Build with Maven
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node: ['10.x']
        java: [1.8]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.os }}-maven-

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn clean install